### ISSUE TITLE
missing linux IVE and IM libraries?

### ISSUE THREAD

**Issue by chalkie666** [linshaova/CUDA_SIMrecon#1]
@linshaova  
After following the build setup instructions in the CMakeLists.txt file, and running cmake as described, it fails to find IVE and IM libraries on linux 64 bit OS. 
Looks like the linux 32 and 64 bit versions of libraries are not included in this repository?
Should they be?
Or is this by design?
Besat
Dan

**Comment by chalkie666** [comment]
So if i then use 
ccmake . 
in the build directory, 
and set manually the locations of the IVE and IM library .so or .a files found at
......priism-4.4.0/Linux/x86_64/LIB
then ccmake configured and generated ok, 
but make still fails, as it cant find the header files in the 
.......priism-4.4.0/Linux/x86_64/INCLUDE
directory

I don't see an  option in ccmake to set the location of the header files for those two libs.

So guess the CMakeLists.txt file is broken for linux? 
I'm very happy to help fix...
Best
Dan

**Comment by chalkie666** [comment]
I got it to configure without using ccmake by changing the cudaSirecon/CMakeLists.txt a little to hardcode the location of the priism dir. In the CMakeLists.txt  the comments there above the relevant lines say we assume the user has a correctl set IVE location environment variable... but this is not described in the instructions in the master/top  CMakeLists.txt, so that why it fails, because that environmental variable is not set on a naive system. 

Best
Dan

**Comment by linshaova** [comment]
Hi Dan,

Thanks for your inputs and my apologies for not providing a thorough and correct documentations. So it looks like you've gotten the issues resolved? Were you able to generate executables?

As you can tell, I'm a novice at providing public-domain code and haven't been tending cudaSIMrecon for a while (partly also because of lack of interests so far). I'm willing to learn from you and the community, so please let me know where I should improve besides updating the CMakeLists files.

Thanks again.

lin

**Comment by chalkie666** [comment]
Thanks to you for allowing the community to build and use it!

Not everyone does.
I see no code or downloadable executable  for heinzmanns blind SIM stuff
yet... Maybe i missed it. Should have another look.

Best.
D
